# Generated by Django 3.2.16 on 2022-12-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('fab', models.CharField(blank=True, max_length=1000, null=True)),
                ('wht', models.CharField(blank=True, max_length=1000, null=True)),
                ('twi', models.CharField(blank=True, max_length=1000, null=True)),
                ('lin', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
